FROM almalinux:9

# Repos needed for (VOMS and FTS) and WLCG certs
ADD ca.repo /etc/yum.repos.d/ca.repo
ADD wlcg-el9.repo /etc/yum.repos.d/wlcg-el9.repo

# Enable EPEL
RUN dnf install -y yum-utils \
  && dnf config-manager --set-enabled crb \
  && dnf install -y epel-release


RUN dnf update -y && \
    dnf upgrade -y && \
    dnf clean all && \
    rm -rf /var/cache/dnf

    RUN dnf -y install -y httpd python3-pip python3-mod_wsgi python3-devel mod_ssl openssl-devel python3-m2crypto patch xrootd-client && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# Install latest kubectl
RUN curl -o /usr/bin/kubectl -L https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x /usr/bin/kubectl

# Install VOMS and FTS clients for delegating proxies
RUN dnf -y install ca-certificates.noarch ca-policy-lcg fetch-crl voms-clients-cpp fts-rest-cli \
    wlcg-iam-lsc-atlas wlcg-iam-vomses-atlas wlcg-iam-lsc-cms wlcg-iam-vomses-cms \
    python-setuptools python-requests && \
    yum clean all && \
    rm -rf /var/cache/yum

# Install wget
RUN yum -y install wget && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN python3 -m pip install --no-cache-dir --upgrade pip
RUN python3 -m pip install --no-cache-dir --upgrade setuptools
RUN python3 -m pip install --no-cache-dir j2cli

RUN mkdir -p /opt/rucio/certs/
RUN mkdir -p /opt/rucio/kubeconfig/
RUN mkdir -p -m 775 /opt/rucio/fts-delegate/

ADD docker-entrypoint.sh /opt/rucio/fts-delegate/
ADD renew_fts_proxy.sh.j2 /opt/rucio/fts-delegate/
ADD renew_fts_proxy_atlas.sh.j2 /opt/rucio/fts-delegate/
ADD renew_fts_proxy_dteam.sh.j2 /opt/rucio/fts-delegate/
ADD renew_fts_proxy_tutorial.sh.j2 /opt/rucio/fts-delegate/
ADD renew_fts_proxy_multi_vo.sh.j2 /opt/rucio/fts-delegate/
ADD renew_fts_proxy_escape.sh.j2 /opt/rucio/fts-delegate/

ADD vomses/* /etc/vomses/

ENTRYPOINT ["/opt/rucio/fts-delegate/docker-entrypoint.sh"]
