services:
  fts:
    build: .
    hostname: fts
    ports:
      - "8446:8446"
      - "8449:8449"
    depends_on:
      - ftsdb
    networks:
      - fts


  ftsdb:
    image: mysql:8
    hostname: ftsdb
    environment:
      - MYSQL_USER=fts
      - MYSQL_PASSWORD=fts
      - MYSQL_ROOT_PASSWORD=fts
      - MYSQL_DATABASE=fts
    ports:
      - "3306:3306"
    networks:
      - fts
    volumes:
      - ftsdb-data:/var/lib/mysql

networks:
  fts:

volumes:
  ftsdb-data:
