FROM centos:7

RUN yum install -y epel-release.noarch && \
    yum clean all && \
    rm -rf /var/cache/yum
RUN yum upgrade -y && \
    yum clean all && \
    rm -rf /var/cache/yum
RUN yum -y install https://repo.ius.io/ius-release-el7.rpm &&\ 
    yum install -y python36u-pip voms-clients-java gfal2-all gfal2-util gfal2-python3 \
                   nordugrid-arc-client nordugrid-arc-plugins-gfal \
                   nordugrid-arc-plugins-globus nordugrid-arc-plugins-s3 \
                   nordugrid-arc-plugins-xrootd && \
                   yum clean all && \
                   rm -rf /var/cache/yum
#RUN ln -sf python3.6 /usr/bin/python ; ln -sf pip3.6 /usr/bin/pip

# Upgrade pip & setuptools
RUN python3.6 -m pip install --no-cache-dir --upgrade pip
RUN python3.6 -m pip install  --no-cache-dir --upgrade setuptools

# Install Rucio
ARG TAG
RUN python3.6 -m pip install --no-cache-dir --pre rucio-clients==$TAG
RUN python3.6 -m pip install --no-cache-dir jinja2 j2cli pyyaml

COPY rucio.cfg.j2 /

# To generate the configuration and enable bash completion for the rucio clients
ADD bashrc /root/.bashrc

ENV PATH $PATH:/opt/rucio/bin

CMD ["/bin/bash"]
