#! /usr/bin/env python3

import argparse
import hashlib
import subprocess
import time

parser = argparse.ArgumentParser(
    prog='DeterministicDelay',
    description=('Delays running a command by a consistent amount of time. '
                 'This may be useful in spreading the load out from frequently running cronjobs. '
                 'When frequency is specified, delays longer than the frequency will exit without executing, '
                 'and the next execution will have a possibility. '
                 'i.e. -d 7d -f 1d means the script is run once per day, but the only 1/7 executions will really run.'),
    epilog=None)

parser.add_argument('-d', required=False, dest='delay',
                    help=('The maximum amount of time to delay. 60 seconds is the default, '
                          'suffix with s (the default), m, h, or d for seconds, minutes, hours, or days.'))
parser.add_argument('-f', required=False, dest='frequency',
                    help=('Frequency of submission. '
                          'Suffix with s (the default), m, h, or d for seconds, minutes, hours, or days.'))
parser.add_argument('commands', nargs='+', help="The commands to run")
args = parser.parse_args()

command_hash = hashlib.sha256(bytes(str(args.commands), 'utf-8'))
checksum = int(command_hash.hexdigest(), 16)

frequency = None
if args.frequency:
    if args.frequency[-1] in ['s', 'm', 'h', 'd']:
        frequency_value, frequency_unit = args.frequency[:-1], args.frequency[-1]
        if frequency_unit == 'm':
            frequency = int(frequency_value) * 60
        elif frequency_unit == 'h':
            frequency = int(frequency_value) * 60 * 60
        elif frequency_unit == 'd':
            frequency = int(frequency_value) * 24 * 60 * 60
        else:
            frequency = int(frequency_value)
    else:
        frequency = int(args.frequency)

if not args.delay:
    max_delay = 60
else:
    if args.delay[-1] in ['s', 'm', 'h', 'd']:
        delay_value, delay_unit = args.delay[:-1], args.delay[-1]
        if delay_unit == 'm':
            max_delay = int(delay_value) * 60
        elif delay_unit == 'h':
            max_delay = int(delay_value) * 60 * 60
        elif delay_unit == 'd':
            max_delay = int(delay_value) * 24 * 60 * 60
        else:
            max_delay = int(delay_value)
    else:
        max_delay = int(args.delay)

delay = checksum % max_delay

if frequency and delay:
    epoch = time.time()
    if epoch % delay > frequency:
        print(f'Exiting. time: {epoch % max_delay} max: {max_delay} f: {frequency}')
        exit()
    else:
        print(f'Running. time: {epoch % max_delay} max: {max_delay} f: {frequency}')
        delay = checksum % frequency

print(f"Sleeping {delay}s")
time.sleep(delay)

executed = subprocess.run(args.commands, capture_output=True)

print("STDOUT")
print(executed.stdout)
print("STDERR")
print(executed.stderr)
