name: org-secrets

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Secrets are set
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
            echo "DOCKER_HUB_USERNAME is not set. Exiting!"
            exit 1
          fi
          if [ -z "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" ]; then
            echo "DOCKER_HUB_ACCESS_TOKEN is not set. Exiting!"
            exit 1
          fi
      - name: Verify Length of Secrets is not zero
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          if [ ${#DOCKER_HUB_USERNAME} -eq 0 ]; then
            echo "DOCKER_HUB_USERNAME is not set. Exiting!"
            exit 1
          fi
          if [ ${#DOCKER_HUB_ACCESS_TOKEN} -eq 0 ]; then
            echo "DOCKER_HUB_ACCESS_TOKEN is not set. Exiting!"
            exit 1
